stages:
#  preparedvc:
#    cmd: stage add -n split_data -d models/split_data.py -d data/raw_data/data.csv
#      -o data/processed_data/X_train.csv -o data/processed_data/X_test.csv -o data/processed_data/y_train.csv
#      -o data/processed_data/y_test.csv python models/split_data.py
  split_data:
    cmd: python models/1_data_splitting.py
    deps:
    - data/raw_data/raw.csv
    - models/1_data_splitting.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize_data:
    cmd: python models/2_data_normalization.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - models/2_data_normalization.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python models/3_gridsearch_best_params.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/3_gridsearch_best_params.py
    outs:
    - src/models/best_params.pkl
  train_model:
    cmd: python models/4_model_training.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/best_params.pkl
    - models/4_model_training.py
    outs:
    - src/models/final_model.pkl
  evaluate_model:
    cmd: python models/5_model_evaluation.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/5_model_evaluation.py
    - src/models/final_model.pkl
    outs:
    - data/predictions.csv
    - metrics/scores.json

